source "https://rubygems.org"

gem "just-the-docs"
gem "jekyll", "~> 4", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
